name: Download WeChat JS-SDK

on:
  push:
    tags:
      - '*'

jobs:
  download-sdk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Extract version from tag
        id: get_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Tag: $TAG_NAME, Version: $VERSION"
          
      - name: Download WeChat JS-SDK
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          URL="http://res.wx.qq.com/open/js/jweixin-${VERSION}.js"
          echo "Downloading from: $URL"
          curl -o index.js "$URL"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.js
          git commit -m "Update WeChat JS-SDK to version ${{ steps.get_version.outputs.version }}" || exit 0
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
