name: Download WeChat JS-SDK

on:
  push:
    branches:
      - main

jobs:
  download-sdk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
        
      - name: Check if .versionrc was modified
        id: check_versionrc
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^\.versionrc$"; then
            echo "versionrc_changed=true" >> $GITHUB_OUTPUT
            echo ".versionrc file was modified"
          else
            echo "versionrc_changed=false" >> $GITHUB_OUTPUT
            echo ".versionrc file was not modified"
          fi
          
      - name: Download WeChat JS-SDK versions
        if: steps.check_versionrc.outputs.versionrc_changed == 'true'
        run: |
          if [ ! -f .versionrc ]; then
            echo ".versionrc file not found"
            exit 1
          fi
          
          mkdir -p lib
          
          while IFS= read -r version; do
            if [ ! -z "$version" ]; then
              echo "Processing version: $version"
              mkdir -p "lib/$version"
              URL="http://res.wx.qq.com/open/js/jweixin-${version}.js"
              echo "Downloading from: $URL"
              curl -o "lib/$version/index.js" "$URL"
              if [ $? -eq 0 ]; then
                echo "Successfully downloaded version $version"
              else
                echo "Failed to download version $version"
              fi
            fi
          done < .versionrc
          
      - name: Commit and push changes
        if: steps.check_versionrc.outputs.versionrc_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lib/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update WeChat JS-SDK versions from .versionrc"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
