name: Update WeChat JS SDK

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  update-sdk:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - run: pnpm install
        
      - run: pnpm run download

      - run: pnpm run update:meta
        
      - name: Check for changes and commit
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "chore: update WeChat JS SDK files"
            git push
          else
            echo "No changes to commit"
          fi
